add_library(listener STATIC listener.cpp)
add_library(session STATIC session.cpp)
add_library(response_handler INTERFACE)
add_library(simdjson STATIC simdjson.cpp)
add_library(class_common INTERFACE)

target_include_directories(listener PUBLIC class_common)
target_include_directories(session PUBLIC class_common)
target_include_directories(response_handler INTERFACE class_common)
target_include_directories(simdjson PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_include_directories(class_common INTERFACE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/..)

target_link_libraries(class_common INTERFACE Boost::filesystem Boost::system Boost::json helper)
target_link_libraries(listener PUBLIC Boost::filesystem Boost::system Boost::json helper session)
target_link_libraries(session PUBLIC class_common )
target_link_libraries(response_handler INTERFACE Boost::system Boost::json)